### ISSUE TITLE
check if there are issues on the bars on the legacy label

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#124]
while working on #121 and #123, I noticed that there are cases where the bars are a lot thicker and found that this is because there are cases where the bottom bar or top bar (thin line) are present when they shouldn't be

when I find the time, I need to check if this bug is also present on the legacy label

cc @mattsilv to keep him informed

**Comment by majin22** [comment]
using this debug css code, it shows that this is an issue on the legacy admin
```css
.nutritionLabel .line {
	border-top: 10px solid red;
}

.nutritionLabel .tblCalorieDiet th {
	border-bottom: 13px solid green;
}

.nutritionLabel .bar1 {
	height: 20px;
	background: #f2a50a;
}

.nutritionLabel .bar2 {
	height: 15px;
	background: #f52ff5;
}
```

there should be no 2 colors on top of each other as that's the reason why there are cases where the black links are thicker than normal

![Legacy Version Demo Page](https://user-images.githubusercontent.com/271582/76693065-406b6c00-669a-11ea-9440-70d48e0c5996.png)
