### ISSUE TITLE
add the bootstrap sr-only class to the css

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#83]
```css
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0 0 0 0);
  border: 0;
}
```
